### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 111678900** [yala/Mirai#10]
Could you please tell me where the JSON file comes from? Earlier, didn't it involve generating PNG images from DICOM files? So where does this JSON file come from?OncoNet main running from commit: 

f96f180243140b3c668f5f0507ad1f14d2d27aa1
Update README.mdauthor: Adam Yala, date: 1695579050

Loading data-augmentation scheme...

Loading data...
Traceback (most recent call last):
  File "/root/Mirai/onconet/datasets/abstract_onco_dataset.py", line 51, in __init__
    self.metadata_json = json.load(open(args.metadata_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/AsymMirai/example_data_format.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/main.py", line 47, in <module>
    train_data, dev_data, test_data = dataset_factory.get_dataset(args, transformers, test_transformers)
  File "/root/Mirai/onconet/datasets/factory.py", line 50, in get_dataset
    train = dataset_class(args, transformers, 'train')
  File "/root/Mirai/onconet/datasets/abstract_onco_dataset.py", line 57, in __init__
    raise Exception(METAFILE_NOTFOUND_ERR.format(args.metadata_path, e))
Exception: Metadata file /root/autodl-tmp/AsymMirai/example_data_format.json could not be parsed! Exception: [Errno 2] No such file or directory: '/root/autodl-tmp/AsymMirai/example_data_format.json'!

**Comment by yala** [comment]
From your comment, it looks like you're trying to extend AsymMirai. This isn't directly supported in this codebase and I recommend reaching to authors of asym mirai
